### ISSUE TITLE
HTTP protocol support

### ISSUE THREAD

**Issue by rpalcolea** [breskeby/indexing-metrics-collector#12]
Hi @breskeby ,

The plugin is awesome! I wanted to use it but noticed that the `ElasticsearchClientFactory` created the client with `https` by default. I agree that this is the best to do but unfortunately I'm facing some internal infrastructure issues that prevent me from going this route.

Wondering if you would be open to a PR to address this by allowing folks to configure http vs https as part of `ImcSettingsState`

**Comment by breskeby** [comment]
Hey. Cool that you're interested in the plugin. And of course we're open for PRs

**Comment by rpalcolea** [comment]
Wonder if https://github.com/breskeby/indexing-metrics-collector/pull/13 makes sense

**Comment by breskeby** [comment]
Thanks again for the PR.

This has been merged https://github.com/elastic/idea-indexing-metrics-collector/commit/63baabc3984af86853e0c187d3192dd78c0fec61

I ported the repo to the elastic org before, just in case you want to contribute more PRs idea/idea-indexing-metrics-collector is the right place ;)
